name: Upload Auto-Editor Package
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools build wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PIP_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*
  make:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            arch: arm64
          - os: macos-12
            arch: x86_64
          - os: ubuntu-latest
            arch: i686
          - os: ubuntu-latest
            arch: x86_64
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Build Directory
      run: |
        pip install -U numpy pyav pyinstaller
        pyinstaller auto_editor/__main__.py --strip --optimize 2 \
          --exclude-module yaml --exclude-module numpy.random --exclude-module numpy.fft \
          --hidden-import auto_editor.subcommands.desc \
          --hidden-import auto_editor.subcommands.info --hidden-import auto_editor.subcommands.levels \
          --hidden-import auto_editor.subcommands.palet --hidden-import auto_editor.subcommands.repl \
          --hidden-import auto_editor.subcommands.subdump --hidden-import auto_editor.subcommands.test
    - name: Upload Directory
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.os }}-${{ matrix.arch }}
        path: dist/
